#!/usr/bin/env python3
"""
template_sync.py — publish template-grade changes to the template remote
WITHOUT ever touching research content.

The framework's zoning makes this mechanical: content lives in wiki/, raw/,
experiments/, blog/posts/, and in four "mixed" files (CLAUDE.md §0, index.md,
log.md, ideas/backlog.md). Everything else is template. This script:

  1. fetches the template remote and opens a temp worktree at its main branch;
  2. copies ONLY the template-zone paths from the working repo (content zones
     are not in the manifest — leakage is structurally impossible);
  3. swaps the four mixed files for their pristine forms from
     meta/template-state/ and resets CONTACT_EMAIL to the placeholder;
  4. re-runs the build/lint/test suite inside the worktree as validation;
  5. runs a leakage guard over the staged diff, then commits (and pushes
     with --push).

Usage:
  python scripts/template_sync.py                 # dry run: show what would change
  python scripts/template_sync.py --commit        # commit in the worktree, no push
  python scripts/template_sync.py --push          # commit + push to <remote>/main
  python scripts/template_sync.py --push -m "..." # custom commit message
Options: --remote NAME (default: template, falls back to origin)

Stdlib only.
"""
from __future__ import annotations
import argparse, re, shutil, subprocess, sys, tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Template zone: these paths are copied verbatim (recursively) into the
# template worktree. Content zones (wiki/, raw/, experiments/, blog/posts/)
# are deliberately absent.
TEMPLATE_PATHS = [
    "CLAUDE.md",            # transformed afterwards (§0 reset)
    "README.md",
    "llm-wiki.md",
    "serve.py",
    ".gitignore",
    "scripts",
    "portal",
    "html",
    "blog/build.py",
    "blog/README.md",
    "blog/categories.json",
    "blog/design",
    "meta",
    ".claude/skills",
]

# Mixed files: replaced by their pristine template-state versions.
MIXED = {
    "index.md":         "meta/template-state/index.md",
    "log.md":           "meta/template-state/log.md",
    "ideas/backlog.md": "meta/template-state/backlog.md",
}

# Generated artifacts: removed after copy, regenerated by the validation step.
GENERATED = ["html/portal/index.json", "blog/index.json"]

# Leakage guard: staged paths matching these prefixes abort the sync
# (defense in depth — the manifest should make this unreachable).
FORBIDDEN_PREFIXES = ("wiki/", "raw/", "experiments/", "blog/posts/")
FORBIDDEN_ALLOW = {"blog/posts/.gitkeep"}

IGNORE = shutil.ignore_patterns("__pycache__", "*.pyc", ".pytest_cache")

CONTACT_RE = re.compile(r'("DEEPLR_CONTACT_EMAIL",\s*)"[^"]*"')
SECTION0_RE = re.compile(
    r"(## 0\. Project config \(fill in at bootstrap\)\n\n).*?(?=\nThe topic list is mutable)",
    re.DOTALL)


def run(args, cwd=ROOT, check=True, capture=False):
    return subprocess.run(args, cwd=str(cwd), check=check,
                          capture_output=capture, text=True, encoding="utf-8")


def resolve_remote(preferred: str) -> str:
    remotes = run(["git", "remote"], capture=True).stdout.split()
    if preferred in remotes:
        return preferred
    if "origin" in remotes:
        print(f"[sync] remote '{preferred}' not found; using 'origin'")
        return "origin"
    sys.exit("[sync] no usable git remote (expected 'template' or 'origin')")


def copy_path(rel: str, dest_root: Path):
    src = ROOT / rel
    dst = dest_root / rel
    if not src.exists():
        print(f"[sync] WARN: manifest path missing locally: {rel}")
        return
    if src.is_dir():
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst, ignore=IGNORE)
    else:
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)


def transform(dest_root: Path):
    # CLAUDE.md §0 → pristine bootstrap-protocol form.
    claude = dest_root / "CLAUDE.md"
    sec0 = (dest_root / "meta/template-state/claude-md-section0.md").read_text(encoding="utf-8")
    text = claude.read_text(encoding="utf-8")
    new_text, n = SECTION0_RE.subn(lambda m: m.group(1) + sec0.rstrip() + "\n", text)
    if n != 1:
        sys.exit("[sync] CLAUDE.md §0 anchor not found — refusing to publish a "
                 "bootstrapped config. Check the section markers.")
    claude.write_text(new_text, encoding="utf-8")

    # download.py contact email → placeholder.
    dl = dest_root / "scripts/harvest/download.py"
    dtext = dl.read_text(encoding="utf-8")
    dtext, n = CONTACT_RE.subn(r'\1"you@example.com"', dtext)
    if n != 1:
        sys.exit("[sync] CONTACT_EMAIL anchor not found in download.py")
    dl.write_text(dtext, encoding="utf-8")

    # Mixed files → template-state versions.
    for rel, state in MIXED.items():
        dst = dest_root / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(dest_root / state, dst)

    # Drop generated artifacts; validation regenerates them.
    for rel in GENERATED:
        p = dest_root / rel
        if p.exists():
            p.unlink()


def validate(dest_root: Path):
    print("[sync] validating in worktree …")
    py = sys.executable or "python"
    run([py, "-m", "unittest", "discover", "scripts/harvest/tests"], cwd=dest_root)
    run([py, "portal/build.py"], cwd=dest_root)
    run([py, "blog/build.py"], cwd=dest_root)
    run([py, "portal/build.py", "--lint", "--strict"], cwd=dest_root)
    run([py, "blog/build.py", "--lint"], cwd=dest_root)
    print("[sync] validation OK (tests, builds, strict lint)")


def leakage_guard(dest_root: Path):
    staged = run(["git", "diff", "--cached", "--name-only"],
                 cwd=dest_root, capture=True).stdout.splitlines()
    bad = [p for p in staged
           if p.startswith(FORBIDDEN_PREFIXES) and p not in FORBIDDEN_ALLOW]
    if bad:
        sys.exit("[sync] LEAKAGE GUARD TRIPPED — refusing to commit content "
                 "paths to the template:\n  " + "\n  ".join(bad))
    return staged


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--remote", default="template")
    ap.add_argument("--branch", default="main")
    ap.add_argument("--commit", action="store_true", help="commit in worktree")
    ap.add_argument("--push", action="store_true", help="commit and push")
    ap.add_argument("-m", "--message", default="template: sync framework updates")
    args = ap.parse_args()

    remote = resolve_remote(args.remote)
    run(["git", "fetch", remote])

    tmp = Path(tempfile.mkdtemp(prefix="deep-lr-template-"))
    wt = tmp / "wt"
    run(["git", "worktree", "add", "--detach", str(wt), f"{remote}/{args.branch}"])
    try:
        for rel in TEMPLATE_PATHS:
            copy_path(rel, wt)
        transform(wt)
        validate(wt)

        run(["git", "add", "-A"], cwd=wt)
        staged = leakage_guard(wt)
        if not staged:
            print("[sync] template is already up to date — nothing to publish.")
            return 0
        print(f"[sync] {len(staged)} file(s) changed vs {remote}/{args.branch}:")
        print(run(["git", "diff", "--cached", "--stat"], cwd=wt, capture=True).stdout)

        if not (args.commit or args.push):
            print("[sync] DRY RUN — rerun with --commit or --push to publish.")
            return 0

        run(["git", "commit", "-m", args.message], cwd=wt)
        if args.push:
            run(["git", "push", remote, f"HEAD:{args.branch}"], cwd=wt)
            print(f"[sync] pushed to {remote}/{args.branch}")
        else:
            sha = run(["git", "rev-parse", "HEAD"], cwd=wt, capture=True).stdout.strip()
            print(f"[sync] committed {sha[:9]} in worktree (not pushed); "
                  f"push manually or rerun with --push")
        return 0
    finally:
        run(["git", "worktree", "remove", "--force", str(wt)], check=False)
        shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
